erofs-utils: mount: fix type mismatches causing compilation errors
In file included from ../include/erofs/config.h:15,
                 from main.c:14:
main.c: In function ‘erofsmount_tarindex_pread’:
../include/erofs/defs.h:148:24: error: comparison of distinct pointer types lacks a cast [-Werror]
  148 |         (void) (&_min1 == &_min2);              \
      |                        ^~
main.c:380:30: note: in expansion of macro ‘min’
  380 |                 index_part = min(count, tp->tarindex_size - offset);
      |                              ^~~

Fixes: da1fb2864fbb ("erofs-utils: mount: add support for standard OCI targz blob access")
Signed-off-by: Gao Xiang <hsiangkao@linux.alibaba.com>
Link: https://lore.kernel.org/r/20251217080711.1304576-1-hsiangkao@linux.alibaba.com