erofs-utils: loosen hash_64 compile restriction
We've got the below "unused function" warning for 32bit compilation. So,
fixed it.

error: unused function 'hash_64' [-Werror,-Wunused-function]

Link: https://lore.kernel.org/r/20211202190923.975767-1-daeho43@gmail.com
Reviewed-by: Gao Xiang <hsiangkao@linux.alibaba.com>
Signed-off-by: Daeho Jeong <daehojeong@google.com>
Signed-off-by: Gao Xiang <xiang@kernel.org>