erofs-utils: lib: fix false-positive uninitialized variable warning
It may trigger the following warning:

xattr.c: In function ‘erofs_xattr_iter_inline.constprop’:
xattr.c:1349:13: error: ‘ret’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
 1349 |         int ret;
      |             ^~~

'remaining' is always greater than 0. Switch to a do-while loop
to eliminate this false-positive warning.

Link: https://lore.kernel.org/r/20260219192442.2609494-1-hsiangkao@linux.alibaba.com
Signed-off-by: Gao Xiang <hsiangkao@linux.alibaba.com>